// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovswkgujezxwygselcap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92c3drZ3VqZXp4d3lnc2VsY2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0NDUxNzIsImV4cCI6MjA4NDAyMTE3Mn0.TS-IDWedMaO-snNJolAjluN4t3SKv8gFU8-z44uYvE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});